// Animesh Koley [23 Jul 2025, 14:17 IST]: This utility is NOT written by me (Animesh Koley), instead this has been generated by Gemini Ai on my prompt
import { Workbook } from 'exceljs';

export async function readKeyValueSheet(filePath, sheetName) {
    const workbook = new Workbook();
    try {
        await workbook.xlsx.readFile(filePath);
        const worksheet = workbook.getWorksheet(sheetName);

        if (!worksheet) {
            throw new Error(`Sheet '${sheetName}' not found in the Excel file.`);
        }

        const data = {};
        worksheet.eachRow((row, rowNumber) => {
            const key = row.getCell(1).value;
            const value = row.getCell(2).value;

            if (key && value) {
                data[key] = value;
            }
        });
        return data;
    } catch (error) {
        console.error(`Error reading Excel file: ${error.message}`);
        throw error;
    }
}